amines homework
CubeADGroup/python-training pull request #6
Opened 2017-09-10 03:52 UTC by aminecym

question: 类变量的初始化，需要填写默认值吗？

2017-09-11 07:39 UTC, lovemyliwu requested changes
please check comments

2017-09-11 07:39 UTC, lovemyliwu commented on homework/amine/main.py
> +            f.writelines('标题:{},  作者:{}\n'.format(bm.title, bm.name))
writelines是用来写list的

2017-09-11 07:39 UTC, lovemyliwu commented on homework/amine/main.py
> +            bm.user_Id = book['userId']
Python里变量都是小写

2017-09-11 07:39 UTC, lovemyliwu commented on homework/amine/main.py
> +            bm.name = bm.set_name_from_id(bm.user_Id, users)
从你这用法来看, 方法名为get_xxx更为合适

2017-09-11 07:39 UTC, lovemyliwu commented on homework/amine/models.py
> +    user_Id = int()
为什么是类变量?

2017-09-11 07:39 UTC, lovemyliwu commented on homework/amine/models.py
> +        pass
为什么不是实例变量

2017-09-11 07:42 UTC, aminecym commented on homework/amine/main.py
> +            bm.name = bm.set_name_from_id(bm.user_Id, users)
不是给bookModel这个类新增了一个name的变量的嘛。get不是获取的意思吗？

2017-09-11 07:47 UTC, aminecym commented on homework/amine/models.py
> +    user_Id = int()
还想着声明实例的时候要给定值，就弄成了类变量。不过又一想，这两个属性都是变化的，还是用实例属性吧。

2017-09-11 07:48 UTC, aminecym commented on homework/amine/models.py
> +        pass
replied

2017-09-11 07:48 UTC, aminecym commented on homework/amine/main.py
> +            bm.user_Id = book['userId']
replied

2017-09-12 08:58 UTC, lovemyliwu commented on homework/amine/main.py
> +            bm.name = bm.set_name_from_id(bm.user_Id, users)
set_xxx不应该有返回值

2017-09-12 08:59 UTC, lovemyliwu requested changes
请删除没用的文件, 例如.DS_Store, *.pyc等

2017-09-12 08:59 UTC, lovemyliwu commented on homework/amine/models.py
> +    def print_model(self):
未使用的方法

2017-09-12 09:00 UTC, lovemyliwu commented on homework/amine/main.py
> +            bm.name = bm.set_name_from_id(bm.user_id, users)
set_xxx一般没有返回值

2017-09-12 09:55 UTC, lovemyliwu requested changes
check comment

2017-09-12 09:55 UTC, lovemyliwu commented on homework/amine/models.py
> +            self.name = "None"
不是已经有默认值None了吗?为什么还要这么做?

2017-09-12 10:01 UTC, lovemyliwu approved these changes

2017-09-12 10:56 UTC, merged